[workspace]
members = ["shared", "evergreen", "alzahra"]
resolver = "2"

[workspace.package]
# name = "persian-gulf"
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
log = "0.4.22"
toml = "0.9.10"
rand = "0.9.2"
tokio = { version = "1.40.0", features = ["full"] }
serde = { version = "1.0.210", features = ["derive"] }

shared = { path = "./shared" }
